name: Build Test

# # This workflow uses actions that are not certified by GitHub.
# # They are provided by a third-party and are governed by
# # separate terms of service, privacy policy, and support
# # documentation.

on:
  pull_request:
    branches: [ "main" ]
  
jobs:
  build_test: 
    uses: iit-DLSLab/cicd_tools/.github/workflows/dls2_build_test.yml@main
    with:
      test-command: "ls"
      build-script-path: .github/scripts/install_dls2_msgs.sh
      cmake-arguments: "-DBUILD_DLS2_MSGS=OFF"
    secrets:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      CICD_PAT: ${{ secrets.CICD_PAT }}