name: Create Release and .deb Files Project

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-rc*'

env:
  GNUTLS_CPUID_OVERRIDE: 0x1

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build_test:
    uses: iit-DLSLab/cicd_tools/.github/workflows/dls2_build_test.yml@main
    with:
      test-command: "ls"
      output_workflow_artifact_name: build
    secrets:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      CICD_PAT: ${{ secrets.CICD_PAT }}

  release_deb:
    needs: build_test
    uses: iit-DLSLab/cicd_tools/.github/workflows/create-release-deb.yml@main
    with:
      package-name: "dls2"
      deb-script-path: "scripts/create-deb-deploy.sh"
      container: "ghcr.io/iit-dlslab/dls2-dev:latest"
      workflow_artifact_name: ${{ needs.build_test.outputs.build_workflow_artifact_name }}
      artifact_download_path: "."
    secrets:
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      CICD_PAT: ${{ secrets.CICD_PAT }}

  publish_runtime_image:
    needs: release_deb
    uses: iit-DLSLab/cicd_tools/.github/workflows/docker-publish.yml@main
    with:
      image_name: dls2-runtime
      registry: ghcr.io
      registry_pull_scope: iit-dlslab/dls2-dev@pull
      context: external-docker/dockerfiles/dls2-dev-deb
      dockerfile: external-docker/dockerfiles/dls2-dev-deb/Dockerfile
      tag_override: ${{ needs.release_deb.outputs.version_tag }}
      workflow_artifact_name: ${{ needs.release_deb.outputs.runtime_deb_workflow_artifact_name }}
      artifact_download_path: external-docker/dockerfiles/dls2-dev-deb/artifacts
      extra_checkout_repository: iit-DLSLab/dls_docker
      extra_checkout_ref: deb
      extra_checkout_path: external-docker
      extra_build_args: |
        DLS2_DEB_FILE=${{ needs.release_deb.outputs.runtime_deb_artifact_name }}
      force_latest_tag: true
    secrets:
      CICD_PAT: ${{ secrets.CICD_PAT }}

  publish_framework_image:
    needs: release_deb
    uses: iit-DLSLab/cicd_tools/.github/workflows/docker-publish.yml@main
    with:
      image_name: dls2-framework
      registry: ghcr.io
      registry_pull_scope: iit-dlslab/dls2-dev@pull
      context: external-docker/dockerfiles/dls2-dev-deb
      dockerfile: external-docker/dockerfiles/dls2-dev-deb/Dockerfile
      tag_override: ${{ needs.release_deb.outputs.version_tag }}
      workflow_artifact_name: ${{ needs.release_deb.outputs.framework_deb_workflow_artifact_name }}
      artifact_download_path: external-docker/dockerfiles/dls2-dev-deb/artifacts
      extra_checkout_repository: iit-DLSLab/dls_docker
      extra_checkout_ref: deb
      extra_checkout_path: external-docker
      extra_build_args: |
        DLS2_DEB_FILE=${{ needs.release_deb.outputs.framework_deb_artifact_name }}
      force_latest_tag: true
    secrets:
      CICD_PAT: ${{ secrets.CICD_PAT }}
